# ------------------------------------------------------------
# Role: process_user 
#
# Apply changes for a single RACF user.
# -----------------------------------------------------------

- name: Obtain RACF user definition
  ibm.ibm_zos_core.zos_tso_command:
    commands:
      - "LISTUSER {{ desired_user.name }}"
  register: user_info
  failed_when: false
  changed_when: false

- name: Show raw LISTUSER output
  ansible.builtin.debug:
    var: user_info
#    var: user_info.output[0].content
  when: debug | default(false) | bool  

- name: Build current_user dictionary
  ansible.builtin.set_fact:
    current_user: >-
      {{
        user_info.output[0].content
        | parse_listuser(desired_user.name)
      }}

- name: Show current user
  ansible.builtin.debug:
    var: current_user
  when: debug | default(false) | bool

- name: Build reconciliation plan
  ansible.builtin.set_fact:
    plan: "{{ desired_user | compare_user(current_user) }}"

- name: Show reconciliation plan
  ansible.builtin.debug:
    var: plan
  when: debug | default(false) | bool

- name: Build RACF command objects
  ansible.builtin.set_fact:
    racf_commands: "{{ plan | build_commands }}"

- name: Show command objects
  ansible.builtin.debug:
    var: racf_commands
  when: (debug | default(false) | bool) or (dry_run | default(false) | bool)

- name: Log the end of a dry run
  include_role:
    name: write_log
  vars:
    severity: info
    message: "**** Ending dry run. No modifications were made to managed nodes. ****"
  when: dry_run | default(false) | bool

- name: End play if this is a dry run 
  meta: end_play
  when: dry_run | default(false) | bool

- name: Apply updates to node {{ apply_to }}
  include_role:
    name: submit_tso_commands
  vars:
    tso_commands: "{{ racf_commands }}"


