# -----------------------------------------------------------------------------
# Role: verify_profiles    
#
# Check RACF profiles and user/group access on the managed node.
# -----------------------------------------------------------------------------
---
- name: Check RACF profiles and user/group access on the managed node.
  hosts: "{{ apply_to }}"
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:
    - name: placeholder
      ansible.builtin.debug:
        msg: placeholder

