name: DEV01

attributes:
  owner: IBMUSER
  superior: SYS1
  installation_data: NEW AND IMPROVED DEVELOPMENT GROUP
  model_dataset: null
  termuacc: false

connections:
  - userid: USER01
    authority: USE
