# ------------------------------------------------------------
# Role: process_groups
#
# Apply changes to RACF Groups based on declarative
# definitions managed under version control.
# ------------------------------------------------------------

- name: Find group definition files
  ansible.builtin.find:
    paths: "{{ racf_definitions }}/groups"
    patterns: "*.yml"
  delegate_to: localhost
  register: group_files

- name: Show group definition files
  ansible.builtin.debug:
    var: group_files
  when: debug | default(false) | bool  

- name: Process each group
  ansible.builtin.include_tasks: process_group.yml
  loop: "{{ group_files.files }}"
  loop_control:
    loop_var: group_file
  vars:
    desired_group: "{{ lookup('file', group_file.path) | from_yaml }}"
  when: group_files.files | length > 0

- name: No group definitions found 
  # This means there are no group definitions to apply to the managed node
  include_role:
      name: write_log
  vars:    
    severity: error
    message: "No group definition files were found at {{ racf_definitions }}/groups."
  ignore_errors: true
  when: group_files.files | length == 0

- name: End play
  meta: end_play
  when: group_files.files | length == 0
