- name: Get RACF group info and set group existence indicator
  ibm.ibm_zos_core.zos_tso_command:
    commands:
      - "listgrp {{ racf_group }}"
  register: group_info
  ignore_errors: true

- name: Set group existence indicator 
  set_fact:
    group_exists: "{{ not group_info.output[0].failed }}"
  ignore_errors: true
