# Variables used in playbooks that issue RACF commands to z/OS.

# ------------------------------------------------------------------
# apply_to: host name
#
# Specifies which group of hosts is to be the target of the playbook.
 
apply_to: zoslab

# ------------------------------------------------------------------
# initlog: true|false
#
# Controls whether the RACF audit log is cleared (deleted) at the
# start of the "Update RACF Definitions" playbook. When set to
# false, messages will be appended to the existing log file.

initlog: true

# -----------------------------------------------------------------
# logfile: path to the RACF audit log file.
#
# Relative paths are interpreted relative to [project_root]/playbooks.
# Absolute paths can be specified, but this is less portable.

logfile: ../logs/racf_audit.log

# -----------------------------------------------------------------
# loglevel: info|warning|error|none
#
# Controls which level of messages are written to the RACF audit log.
#
# info: error, warning, and informational messages
# warning: error and warning messages
# error: error messages
# none: no messages

loglevel: info

# -----------------------------------------------------------------
# racf_profiles: path to the directory tree containing RACF profiles.
#
# Tells the playbook where to find RACF profile information to be
# applied to the managed nodes. Define the default value here. 
#
# You can organize different sets of profiles and point to a
# specific one by setting this variable on the command line:
#
# -e "racf_profiles=path"
# 
# Relative paths are interpreted relative to [project_root]/playbooks.

racf_profiles: "{{ project_root }}/racf_profiles"


